### ISSUE TITLE
Angularjs files missing

### ISSUE THREAD

**Issue by shahzadthathal** [neattutorials/angularjs-yii2-part-2-authentication#1]
Hi,
I just cloned your repository,
Yii main directory vendor always missing,
 also angularjs files missing too.
Can you see into this issue please.

**Comment by neattutorials** [comment]
Hi. You have to install them using composer. I mentioned this in the [README](https://github.com/neattutorials/angularjs-yii2-part-2-authentication/blob/master/README.md).

If you don't have composer [here's how to install it](https://getcomposer.org/doc/00-intro.md#installation-nix).
After installing composer you need to install fxp/composer-asset-plugin by running this command 

```
php composer.phar global require "fxp/composer-asset-plugin:1.0.0"
```

or if you're using windows

```
composer global require "fxp/composer-asset-plugin:1.0.0"
```

Then you can follow the instructions from the README.
